FROM rust:latest as builder

WORKDIR /app
ADD Cargo.toml Cargo.lock ./
ADD src src/
ADD static static/
ADD templates templates/
RUN rustup default nightly
RUN cargo build --release

FROM --platform=linux/arm64 arm64v8/debian:bookworm-slim
COPY --from=builder /app/target/release/website /app/website
COPY --from=builder /app/static/ /app/static/
COPY --from=builder /app/templates/ /app/templates/

EXPOSE 8000
ENV ROCKET_ADDRESS=0.0.0.0

CMD ["sh","-c","cd /app && ./website"]